### ISSUE TITLE
Upgrade to ud-viz version 3.0.0

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz-Template#44]
UD-Viz-template is currently using [ud-viz version 2.38.1](https://github.com/VCityTeam/UD-Viz-Template/blob/master/package.json#L20). Upgrade to [version 3.0.0](https://www.npmjs.com/package/@ud-viz/node/v/3.0.0).

**Comment by valentinMachado** [comment]
WIP on https://github.com/VCityTeam/UD-Viz-Template/tree/update-with-udviz-3.0.0

**Comment by valentinMachado** [comment]
Some changes are required in @ud-viz, we should wait 3.0.1 version
depends of this https://github.com/VCityTeam/UD-Viz/pull/542

**Comment by mathieuLivebardon** [comment]
I think we should stay on our template/fork system, a [`create-react-app`](https://github.com/facebook/create-react-app) package *like* might be a little bit too big for our needs. However, we can take inspiration from their Readme.md 😅

**Comment by valentinMachado** [comment]
Yes I agree with you, we should then propose an empty project by default and provide documentation to the user about how to transpose an ud-viz example into its empty project ( difference between bundle import for the example and npm import for its project + difference between webpack bundling its javascript for its project and writing directly in .html in example + how to configure its backend writes in packages/node/src for its project and the one writes in /bin/host.js for ud-viz)

**Comment by EricBoix** [comment]
@valentinMachado It would be interesting to document what made you change your mind by summarizing the arguments within [this comparison](https://github.com/VCityTeam/VCity/blob/master/Topic_Meetings/2021/2021_03_05_VMA_EBO.md).

**Comment by valentinMachado** [comment]
@EricBoix I forgot this document, actually we don't change the solution choose at that time which is the solution 3. 

Here we were hesitating between the `git clone + rm .git` method (the current one) and the CLI one "that would achieve the same result" as we said.
In both case we are creating a "no git directory" (a project with a single npm package using ud-viz package before and now a project with npm packages using @ud-viz packages since ud-viz was a **front end framework** and becomes a **full stack framework** with 3.0.0) which I think is still the good approach (no mind change).

As I read the document you referenced, cons of solution 3 are not right:

"Demo Helpers code are (automatically) replicated" <= all js code can be if this is pertinent live in ud-viz and thus be factorized
not sure to understand the second one... 

A con of this approach is more if we were evolving UD-Viz- template "no git directory" structure like I don't know adding some default test structure all projects based on UD-Viz--template will not benefit of the evolution since they are once more "no git directory".

Maybe you want me to document (where ?) what make me choose  `git clone + rm .git` method over CLI one. In that case it just that CLI is better as it's more user friendly + allow some dynamic customization but require more time of development which we cant afford.

**Comment by valentinMachado** [comment]
@mathieuLivebardon I am doing the beta tester of ud-viz template since I am using it to start Galeri3 project, the reload feature looks cool but everytime I changed something in the code that trigger a rebuild I loose focus of vscode to my browser lol

**Comment by valentinMachado** [comment]
since we integrate in webpack a css bundler we coudl add a default css file in source imported in webpack
